spring:
  application:
    name: SpringCloudStream
  cloud:
    stream:
      bindings:
        OutputChannelKafka:
          destination: kafka-channel
          binder: kafka
        InputChannelKafka:
          destination: kafka-channel
          binder: kafka
        OutputChannelRabbit:
          destination: rabbit-channel
          binder: rabbit
        InputChannelRabbit:
          destination: rabbit-channel
          binder: rabbit

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 29092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

server:
  port: 8200